defmodule FazouraWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fazoura

  # The session is signed *and* encrypted: it only ever carries the admin flag, but a
  # signed-only cookie is readable by anyone holding it, and there is no reason to
  # publish even that. `secure` keeps it off plaintext connections in production, where
  # the endpoint is HTTPS-only (`force_ssl` in prod.exs).
  @session_options [
    store: :cookie,
    key: "_fazoura_key",
    signing_salt: "b7CtClpQ",
    encryption_salt: "kRv2mQ8x",
    same_site: "Lax",
    secure: Application.compile_env(:fazoura, :secure_cookies, false),
    http_only: true
  ]

  # A private quiz reaches its room inline, photos and all, in one frame
  # (QUIZ_FORMAT.md §5.7). Photos travel as base64, a third bigger, so the 8 MiB
  # `Fazoura.Quizzes.max_inline_bytes/0` needs ~11.2 MB of frame before the document
  # around it. Without this the adapter's own 10 MB limit applies, and a frame over it
  # drops the connection without a word; with it, the server's cap — which answers
  # with a proper error — is the one a user meets. A test holds the two together.
  @max_frame_size 14_000_000

  @doc "The largest websocket frame the room socket accepts."
  def max_frame_size, do: @max_frame_size

  socket "/socket", FazouraWeb.UserSocket,
    # The address is what a ban from public rooms holds on to (FazouraWeb.ClientIp).
    websocket: [connect_info: [:peer_data, :x_headers], max_frame_size: @max_frame_size],
    longpoll: false

  # Admin dashboard LiveViews; the session carries the admin flag (Plugs.AdminAuth).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fazoura,
    gzip: not code_reloading?,
    only: FazouraWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader

    if Application.compile_env(:fazoura, :start_repo, true) do
      plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fazoura
    end
  end

  plug FazouraWeb.Plugs.CORS
  plug FazouraWeb.Plugs.Uploads

  # The dashboard's only JavaScript, served straight from the deps (no asset pipeline).
  plug Plug.Static,
    at: "/admin/js/phoenix",
    from: {:phoenix, "priv/static"},
    only: ~w(phoenix.min.js)

  plug Plug.Static,
    at: "/admin/js/live",
    from: {:phoenix_live_view, "priv/static"},
    only: ~w(phoenix_live_view.min.js)

  plug Plug.Static,
    at: "/assets",
    from: {:fazoura, "priv"},
    only: ~w(admin.js)

  # The Flutter web app (PWA), when this server is also hosting it.
  plug FazouraWeb.Plugs.WebApp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Two things carry a whole quiz with its photos: room creation, which sends a private
  # quiz inline (QUIZ_FORMAT.md §5.8), and publishing, which sends a `.fazoura` package
  # (§5.4, §5.5) — both bounded by `Fazoura.Quizzes.Archive.max_bytes/0`. Everywhere else
  # a body that large is either a mistake or an attempt to make the server buffer
  # megabytes for free, so the general limit is small and the large one is scoped to the
  # routes that need it.
  plug FazouraWeb.Plugs.BodyLimit,
    default: 1_000_000,
    routes: %{
      ["api", "rooms"] => 32_000_000,
      ["api", "quizzes"] => 32_000_000,
      ["api", "quizzes", :_] => 32_000_000,
      ["api", "images"] => 4_000_000
    }

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # The per-route limit above is what actually bounds a body; this is the ceiling.
    length: 32_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FazouraWeb.Router
end
