defmodule FazouraWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fazoura

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fazoura_key",
    signing_salt: "b7CtClpQ",
    same_site: "Lax"
  ]

  socket "/socket", FazouraWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Admin dashboard LiveViews; the session carries the admin flag (Plugs.AdminAuth).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fazoura,
    gzip: not code_reloading?,
    only: FazouraWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader

    if Application.compile_env(:fazoura, :start_repo, true) do
      plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fazoura
    end
  end

  plug FazouraWeb.Plugs.CORS
  plug FazouraWeb.Plugs.Uploads

  # The dashboard's only JavaScript, served straight from the deps (no asset pipeline).
  plug Plug.Static,
    at: "/admin/js/phoenix",
    from: {:phoenix, "priv/static"},
    only: ~w(phoenix.min.js)

  plug Plug.Static,
    at: "/admin/js/live",
    from: {:phoenix_live_view, "priv/static"},
    only: ~w(phoenix_live_view.min.js)

  # The Flutter web app (PWA), when this server is also hosting it.
  plug FazouraWeb.Plugs.WebApp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Private quizzes arrive inline with base64 photos (QUIZ_FORMAT.md §5.7).
    length: 32_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FazouraWeb.Router
end
